# This file was auto-generated by Fern from our API Definition.

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .resources.accounts.client import AccountsClient, AsyncAccountsClient
from .resources.companies.client import AsyncCompaniesClient, CompaniesClient
from .resources.connect_sessions.client import AsyncConnectSessionsClient, ConnectSessionsClient
from .resources.employees.client import AsyncEmployeesClient, EmployeesClient
from .resources.employments.client import AsyncEmploymentsClient, EmploymentsClient
from .resources.locations.client import AsyncLocationsClient, LocationsClient


class HrisClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper
        self.connect_sessions = ConnectSessionsClient(client_wrapper=self._client_wrapper)
        self.accounts = AccountsClient(client_wrapper=self._client_wrapper)
        self.companies = CompaniesClient(client_wrapper=self._client_wrapper)
        self.employees = EmployeesClient(client_wrapper=self._client_wrapper)
        self.employments = EmploymentsClient(client_wrapper=self._client_wrapper)
        self.locations = LocationsClient(client_wrapper=self._client_wrapper)


class AsyncHrisClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper
        self.connect_sessions = AsyncConnectSessionsClient(client_wrapper=self._client_wrapper)
        self.accounts = AsyncAccountsClient(client_wrapper=self._client_wrapper)
        self.companies = AsyncCompaniesClient(client_wrapper=self._client_wrapper)
        self.employees = AsyncEmployeesClient(client_wrapper=self._client_wrapper)
        self.employments = AsyncEmploymentsClient(client_wrapper=self._client_wrapper)
        self.locations = AsyncLocationsClient(client_wrapper=self._client_wrapper)
