# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sanctumlabs/messageschema/common/v1/address.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1sanctumlabs/messageschema/common/v1/address.proto\x12#sanctumlabs.messageschema.common.v1\x1a\x17validate/validate.proto\"\xa5\x03\n\x07\x41\x64\x64ress\x12#\n\raddress_line1\x18\x01 \x01(\tR\x0c\x61\x64\x64ressLine1\x12(\n\raddress_line2\x18\x02 \x01(\tH\x00R\x0c\x61\x64\x64ressLine2\x88\x01\x01\x12\x16\n\x06suburb\x18\x03 \x01(\tR\x06suburb\x12\x12\n\x04\x63ity\x18\x04 \x01(\tR\x04\x63ity\x12\x1f\n\x08province\x18\x05 \x01(\tH\x01R\x08province\x88\x01\x01\x12$\n\x0bpostal_code\x18\x06 \x01(\tH\x02R\npostalCode\x88\x01\x01\x12\x18\n\x07\x63ountry\x18\x07 \x01(\tR\x07\x63ountry\x12\x38\n\x08latitude\x18\x08 \x01(\x01\x42\x17\xfa\x42\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80V@)\x00\x00\x00\x00\x00\x80V\xc0H\x03R\x08latitude\x88\x01\x01\x12:\n\tlongitude\x18\t \x01(\x01\x42\x17\xfa\x42\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80\x66@)\x00\x00\x00\x00\x00\x80\x66\xc0H\x04R\tlongitude\x88\x01\x01\x42\x10\n\x0e_address_line2B\x0b\n\t_provinceB\x0e\n\x0c_postal_codeB\x0b\n\t_latitudeB\x0c\n\n_longitudeBh\n\'com.sanctumlabs.messageschema.common.v1B\x0c\x41\x64\x64ressProtoP\x01Z-sanctumlabs/libraries/messageschema/common/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sanctumlabs.messageschema.common.v1.address_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\'com.sanctumlabs.messageschema.common.v1B\014AddressProtoP\001Z-sanctumlabs/libraries/messageschema/common/v1'
  _ADDRESS.fields_by_name['latitude']._options = None
  _ADDRESS.fields_by_name['latitude']._serialized_options = b'\372B\024\022\022\031\000\000\000\000\000\200V@)\000\000\000\000\000\200V\300'
  _ADDRESS.fields_by_name['longitude']._options = None
  _ADDRESS.fields_by_name['longitude']._serialized_options = b'\372B\024\022\022\031\000\000\000\000\000\200f@)\000\000\000\000\000\200f\300'
  _globals['_ADDRESS']._serialized_start=116
  _globals['_ADDRESS']._serialized_end=537
# @@protoc_insertion_point(module_scope)
