# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sanctumlabs/messageschema/common/v1/location.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2sanctumlabs/messageschema/common/v1/location.proto\x12#sanctumlabs.messageschema.common.v1\x1a\x17validate/validate.proto\"\xa4\x01\n\x08Location\x12\x33\n\x08latitude\x18\x01 \x01(\x01\x42\x17\xfa\x42\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80V@)\x00\x00\x00\x00\x00\x80V\xc0R\x08latitude\x12\x35\n\tlongitude\x18\x02 \x01(\x01\x42\x17\xfa\x42\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80\x66@)\x00\x00\x00\x00\x00\x80\x66\xc0R\tlongitude\x12\x1f\n\x08\x61\x63\x63uracy\x18\x03 \x01(\x01H\x00R\x08\x61\x63\x63uracy\x88\x01\x01\x42\x0b\n\t_accuracyBi\n\'com.sanctumlabs.messageschema.common.v1B\rLocationProtoP\x01Z-sanctumlabs/libraries/messageschema/common/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sanctumlabs.messageschema.common.v1.location_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\'com.sanctumlabs.messageschema.common.v1B\rLocationProtoP\001Z-sanctumlabs/libraries/messageschema/common/v1'
  _LOCATION.fields_by_name['latitude']._options = None
  _LOCATION.fields_by_name['latitude']._serialized_options = b'\372B\024\022\022\031\000\000\000\000\000\200V@)\000\000\000\000\000\200V\300'
  _LOCATION.fields_by_name['longitude']._options = None
  _LOCATION.fields_by_name['longitude']._serialized_options = b'\372B\024\022\022\031\000\000\000\000\000\200f@)\000\000\000\000\000\200f\300'
  _globals['_LOCATION']._serialized_start=117
  _globals['_LOCATION']._serialized_end=281
# @@protoc_insertion_point(module_scope)
