# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sanctumlabs/messageschema/common/v1/money.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/sanctumlabs/messageschema/common/v1/money.proto\x12#sanctumlabs.messageschema.common.v1\x1a\x17validate/validate.proto\"t\n\x05Money\x12\x14\n\x05\x63\x65nts\x18\x01 \x01(\x03R\x05\x63\x65nts\x12U\n\x08\x63urrency\x18\x02 \x01(\x0e\x32-.sanctumlabs.messageschema.common.v1.CurrencyB\n\xfa\x42\x07\x82\x01\x04\x10\x01 \x00R\x08\x63urrency*c\n\x08\x43urrency\x12\x18\n\x14\x43URRENCY_UNSPECIFIED\x10\x00\x12\x07\n\x03ZAR\x10\x01\x12\x07\n\x03MUR\x10\x02\x12\x07\n\x03USD\x10\x03\x12\x07\n\x03\x45UR\x10\x04\x12\x07\n\x03GBP\x10\x05\x12\x07\n\x03RWF\x10\x06\x12\x07\n\x03\x45GP\x10\x07\x42\x66\n\'com.sanctumlabs.messageschema.common.v1B\nMoneyProtoP\x01Z-sanctumlabs/libraries/messageschema/common/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sanctumlabs.messageschema.common.v1.money_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\'com.sanctumlabs.messageschema.common.v1B\nMoneyProtoP\001Z-sanctumlabs/libraries/messageschema/common/v1'
  _MONEY.fields_by_name['currency']._options = None
  _MONEY.fields_by_name['currency']._serialized_options = b'\372B\007\202\001\004\020\001 \000'
  _globals['_CURRENCY']._serialized_start=231
  _globals['_CURRENCY']._serialized_end=330
  _globals['_MONEY']._serialized_start=113
  _globals['_MONEY']._serialized_end=229
# @@protoc_insertion_point(module_scope)
