
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-06T11:00:08+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b8fe9b53207e4d2fe90901bdf2c88f2cc6ff3e49",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
