
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-06T17:22:31-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "47c68a178e4e4521e1ed85e583fc6c6713aaadd8",
 "version": "0.29.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
