
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-06T19:57:39+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "3a31a442686a7172a93cbe8766a153a9af8aad99",
 "version": "0.6.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
