
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-07T17:00:11+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2380d335bea31e7856a377385e9dd471b8a40c64",
 "version": "1.0.34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
