# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai/lzy/v1/common/storage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.lzy.v1.validation import validation_pb2 as ai_dot_lzy_dot_v1_dot_validation_dot_validation__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ai/lzy/v1/common/storage.proto',
  package='ai.lzy.v1.common',
  syntax='proto3',
  serialized_options=b'\n\020ai.lzy.v1.commonB\004LMST',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1e\x61i/lzy/v1/common/storage.proto\x12\x10\x61i.lzy.v1.common\x1a%ai/lzy/v1/validation/validation.proto\"R\n\rS3Credentials\x12\x10\n\x08\x65ndpoint\x18\x01 \x01(\t\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x02 \x01(\t\x12\x1a\n\x0bsecretToken\x18\x03 \x01(\tB\x05\xe8\xc4\x91M\x01\"7\n\x1b\x41zureBlobStorageCredentials\x12\x18\n\x10\x63onnectionString\x18\x01 \x01(\t\"\x9a\x01\n\rStorageConfig\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12-\n\x02s3\x18\x02 \x01(\x0b\x32\x1f.ai.lzy.v1.common.S3CredentialsH\x00\x12>\n\x05\x61zure\x18\x03 \x01(\x0b\x32-.ai.lzy.v1.common.AzureBlobStorageCredentialsH\x00\x42\r\n\x0b\x63redentialsB\x18\n\x10\x61i.lzy.v1.commonB\x04LMSTb\x06proto3'
  ,
  dependencies=[ai_dot_lzy_dot_v1_dot_validation_dot_validation__pb2.DESCRIPTOR,])




_S3CREDENTIALS = _descriptor.Descriptor(
  name='S3Credentials',
  full_name='ai.lzy.v1.common.S3Credentials',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='endpoint', full_name='ai.lzy.v1.common.S3Credentials.endpoint', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accessToken', full_name='ai.lzy.v1.common.S3Credentials.accessToken', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='secretToken', full_name='ai.lzy.v1.common.S3Credentials.secretToken', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\350\304\221M\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=173,
)


_AZUREBLOBSTORAGECREDENTIALS = _descriptor.Descriptor(
  name='AzureBlobStorageCredentials',
  full_name='ai.lzy.v1.common.AzureBlobStorageCredentials',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='connectionString', full_name='ai.lzy.v1.common.AzureBlobStorageCredentials.connectionString', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=230,
)


_STORAGECONFIG = _descriptor.Descriptor(
  name='StorageConfig',
  full_name='ai.lzy.v1.common.StorageConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='ai.lzy.v1.common.StorageConfig.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='s3', full_name='ai.lzy.v1.common.StorageConfig.s3', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='azure', full_name='ai.lzy.v1.common.StorageConfig.azure', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='credentials', full_name='ai.lzy.v1.common.StorageConfig.credentials',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=233,
  serialized_end=387,
)

_STORAGECONFIG.fields_by_name['s3'].message_type = _S3CREDENTIALS
_STORAGECONFIG.fields_by_name['azure'].message_type = _AZUREBLOBSTORAGECREDENTIALS
_STORAGECONFIG.oneofs_by_name['credentials'].fields.append(
  _STORAGECONFIG.fields_by_name['s3'])
_STORAGECONFIG.fields_by_name['s3'].containing_oneof = _STORAGECONFIG.oneofs_by_name['credentials']
_STORAGECONFIG.oneofs_by_name['credentials'].fields.append(
  _STORAGECONFIG.fields_by_name['azure'])
_STORAGECONFIG.fields_by_name['azure'].containing_oneof = _STORAGECONFIG.oneofs_by_name['credentials']
DESCRIPTOR.message_types_by_name['S3Credentials'] = _S3CREDENTIALS
DESCRIPTOR.message_types_by_name['AzureBlobStorageCredentials'] = _AZUREBLOBSTORAGECREDENTIALS
DESCRIPTOR.message_types_by_name['StorageConfig'] = _STORAGECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

S3Credentials = _reflection.GeneratedProtocolMessageType('S3Credentials', (_message.Message,), {
  'DESCRIPTOR' : _S3CREDENTIALS,
  '__module__' : 'ai.lzy.v1.common.storage_pb2'
  # @@protoc_insertion_point(class_scope:ai.lzy.v1.common.S3Credentials)
  })
_sym_db.RegisterMessage(S3Credentials)

AzureBlobStorageCredentials = _reflection.GeneratedProtocolMessageType('AzureBlobStorageCredentials', (_message.Message,), {
  'DESCRIPTOR' : _AZUREBLOBSTORAGECREDENTIALS,
  '__module__' : 'ai.lzy.v1.common.storage_pb2'
  # @@protoc_insertion_point(class_scope:ai.lzy.v1.common.AzureBlobStorageCredentials)
  })
_sym_db.RegisterMessage(AzureBlobStorageCredentials)

StorageConfig = _reflection.GeneratedProtocolMessageType('StorageConfig', (_message.Message,), {
  'DESCRIPTOR' : _STORAGECONFIG,
  '__module__' : 'ai.lzy.v1.common.storage_pb2'
  # @@protoc_insertion_point(class_scope:ai.lzy.v1.common.StorageConfig)
  })
_sym_db.RegisterMessage(StorageConfig)


DESCRIPTOR._options = None
_S3CREDENTIALS.fields_by_name['secretToken']._options = None
# @@protoc_insertion_point(module_scope)
