
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-06T22:17:00+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "4ffc1b71c5b15a8a631b78eaf463ef87b4f4c95e",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
