
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-04T14:52:38+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "39354210f01d5c13c97f63e37e97ff86cb00cf6e",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
