
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-04T18:41:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc553a1a4da4e3fe173d865686a85ec99379461f",
 "version": "2.9.15.post0.dev16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
