# coding: utf-8

"""
    OpenAPI Petstore

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from acme_client.paths.store_order_order_id.delete import DeleteOrder
from acme_client.paths.store_inventory.get import GetInventory
from acme_client.paths.store_order_order_id.get import GetOrderById
from acme_client.paths.store_order.post import PlaceOrder


class StoreApi(
    DeleteOrder,
    GetInventory,
    GetOrderById,
    PlaceOrder,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
