
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-04T10:11:00+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ccae2476565afcbf648dab8704e113e1d777a1d",
 "version": "0.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
