
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-08T17:44:52-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e35ebb72414b2a3c8a73d9cfbee5a6a76d8c0a4",
 "version": "9.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
