
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-04T03:30:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6b58700910c5e2fe442a733b0072bfae208e12f5",
 "version": "1.18.4.post0.dev172"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
