
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-05T02:57:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "824db0a9b9e1a9fc45a0f8aafd533b3687522ff1",
 "version": "1.1.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
