
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-06T14:14:18-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "cf7376a5a2312c1b96d1e0b62fd0a9e84eaa0d58",
 "version": "2.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
