
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-08T16:25:22+1200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b5e183437ebdd5ae2c8e121682ff7bff6f04a041",
 "version": "1.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
