# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tfx/proto/orchestration/metadata.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ml_metadata.proto import metadata_store_pb2 as ml__metadata_dot_proto_dot_metadata__store__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&tfx/proto/orchestration/metadata.proto\x12\x11tfx.orchestration\x1a&ml_metadata/proto/metadata_store.proto\"\xc2\x01\n\x14MLMDConnectionConfig\x12\x43\n\x1a\x64\x61tabase_connection_config\x18\x01 \x01(\x0b\x32\x1d.ml_metadata.ConnectionConfigH\x00\x12J\n\x18mlmd_store_client_config\x18\x02 \x01(\x0b\x32&.ml_metadata.MetadataStoreClientConfigH\x00\x42\x13\n\x11\x63onnection_configJ\x04\x08\x03\x10\x04\"M\n\x11MLMDServiceConfig\x12\r\n\x05owner\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1b\n\x13mlmd_service_target\x18\x03 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tfx.proto.orchestration.metadata_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MLMDCONNECTIONCONFIG._serialized_start=102
  _MLMDCONNECTIONCONFIG._serialized_end=296
  _MLMDSERVICECONFIG._serialized_start=298
  _MLMDSERVICECONFIG._serialized_end=375
# @@protoc_insertion_point(module_scope)
