# coding: utf-8

"""
    scibec

    scibec  # noqa: E501

    The version of the OpenAPI document: 1.6.0
    Contact: klaus.wakonig@psi.ch
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.access_configs_count.get import AccessConfigControllerCount
from openapi_client.paths.access_configs.post import AccessConfigControllerCreate
from openapi_client.paths.access_configs_id.delete import AccessConfigControllerDeleteById
from openapi_client.paths.access_configs.get import AccessConfigControllerFind
from openapi_client.paths.access_configs_id.get import AccessConfigControllerFindById
from openapi_client.paths.access_configs.patch import AccessConfigControllerUpdateAll
from openapi_client.paths.access_configs_id.patch import AccessConfigControllerUpdateById


class AccessConfigControllerApi(
    AccessConfigControllerCount,
    AccessConfigControllerCreate,
    AccessConfigControllerDeleteById,
    AccessConfigControllerFind,
    AccessConfigControllerFindById,
    AccessConfigControllerUpdateAll,
    AccessConfigControllerUpdateById,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
