# coding: utf-8

"""
    scibec

    scibec  # noqa: E501

    The version of the OpenAPI document: 1.6.0
    Contact: klaus.wakonig@psi.ch
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.scans_count.get import ScanControllerCount
from openapi_client.paths.scans.post import ScanControllerCreate
from openapi_client.paths.scans_id.delete import ScanControllerDeleteById
from openapi_client.paths.scans.get import ScanControllerFind
from openapi_client.paths.scans_id.get import ScanControllerFindById
from openapi_client.paths.scans.patch import ScanControllerUpdateAll
from openapi_client.paths.scans_id.patch import ScanControllerUpdateById


class ScanControllerApi(
    ScanControllerCount,
    ScanControllerCreate,
    ScanControllerDeleteById,
    ScanControllerFind,
    ScanControllerFindById,
    ScanControllerUpdateAll,
    ScanControllerUpdateById,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
