# coding: utf-8

"""
    scibec

    scibec  # noqa: E501

    The version of the OpenAPI document: 1.6.0
    Contact: klaus.wakonig@psi.ch
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.sessions_count.get import SessionControllerCount
from openapi_client.paths.sessions.post import SessionControllerCreate
from openapi_client.paths.sessions_id.delete import SessionControllerDeleteById
from openapi_client.paths.sessions.get import SessionControllerFind
from openapi_client.paths.sessions_id.get import SessionControllerFindById
from openapi_client.paths.sessions.patch import SessionControllerUpdateAll
from openapi_client.paths.sessions_id.patch import SessionControllerUpdateById


class SessionControllerApi(
    SessionControllerCount,
    SessionControllerCreate,
    SessionControllerDeleteById,
    SessionControllerFind,
    SessionControllerFindById,
    SessionControllerUpdateAll,
    SessionControllerUpdateById,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
