# coding: utf-8

"""
    Oliver API

    Oliver API service  # noqa: E501

    OpenAPI spec version: 3.11.1
    Contact: api@behavioralsignals.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import behavioral_signals_swagger_client_3
from behavioral_signals_swagger_client_3.api.update_processes_status_e_g_to_abort_processing_api import UpdateProcessesStatusEGToAbortProcessingApi  # noqa: E501
from behavioral_signals_swagger_client_3.rest import ApiException


class TestUpdateProcessesStatusEGToAbortProcessingApi(unittest.TestCase):
    """UpdateProcessesStatusEGToAbortProcessingApi unit test stubs"""

    def setUp(self):
        self.api = behavioral_signals_swagger_client_3.api.update_processes_status_e_g_to_abort_processing_api.UpdateProcessesStatusEGToAbortProcessingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_update_processes(self):
        """Test case for update_processes

        """
        pass


if __name__ == '__main__':
    unittest.main()
