# coding: utf-8

"""
    Oliver API

    Oliver API service  # noqa: E501

    OpenAPI spec version: 3.11.1
    Contact: api@behavioralsignals.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import behavioral_signals_swagger_client_3
from behavioral_signals_swagger_client_3.models.callflow_events import CallflowEvents  # noqa: E501
from behavioral_signals_swagger_client_3.rest import ApiException


class TestCallflowEvents(unittest.TestCase):
    """CallflowEvents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCallflowEvents(self):
        """Test CallflowEvents"""
        # FIXME: construct object with mandatory attributes with example values
        # model = behavioral_signals_swagger_client_3.models.callflow_events.CallflowEvents()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
