
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-07T07:36:40+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "c808b4e3eb342dc04134f7d77c9fb7df36b03831",
 "version": "0.0.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
