"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import ansys.api.geometry.v0.designs_pb2
import ansys.api.geometry.v0.models_pb2
import grpc

class DesignsStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    Get: grpc.UnaryUnaryMultiCallable[
        ansys.api.geometry.v0.models_pb2.EntityIdentifier,
        ansys.api.geometry.v0.models_pb2.Design] = ...

    GetAll: grpc.UnaryUnaryMultiCallable[
        ansys.api.geometry.v0.models_pb2.Empty,
        ansys.api.geometry.v0.designs_pb2.GetAllResponse] = ...

    GetActive: grpc.UnaryUnaryMultiCallable[
        ansys.api.geometry.v0.models_pb2.Empty,
        ansys.api.geometry.v0.models_pb2.Design] = ...

    PutActive: grpc.UnaryUnaryMultiCallable[
        ansys.api.geometry.v0.models_pb2.EntityIdentifier,
        ansys.api.geometry.v0.models_pb2.Empty] = ...

    Open: grpc.UnaryUnaryMultiCallable[
        ansys.api.geometry.v0.designs_pb2.OpenRequest,
        ansys.api.geometry.v0.models_pb2.EntityIdentifier] = ...

    New: grpc.UnaryUnaryMultiCallable[
        ansys.api.geometry.v0.designs_pb2.NewRequest,
        ansys.api.geometry.v0.models_pb2.Design] = ...

    Close: grpc.UnaryUnaryMultiCallable[
        ansys.api.geometry.v0.models_pb2.EntityIdentifier,
        ansys.api.geometry.v0.models_pb2.Empty] = ...

    Save: grpc.UnaryUnaryMultiCallable[
        ansys.api.geometry.v0.models_pb2.EntityIdentifier,
        ansys.api.geometry.v0.models_pb2.Empty] = ...

    SaveAs: grpc.UnaryUnaryMultiCallable[
        ansys.api.geometry.v0.designs_pb2.SaveAsRequest,
        ansys.api.geometry.v0.models_pb2.EntityIdentifier] = ...

    Insert: grpc.UnaryUnaryMultiCallable[
        ansys.api.geometry.v0.designs_pb2.InsertRequest,
        ansys.api.geometry.v0.models_pb2.EntityIdentifier] = ...

    Export: grpc.UnaryUnaryMultiCallable[
        ansys.api.geometry.v0.designs_pb2.ExportRequest,
        ansys.api.geometry.v0.designs_pb2.ExportResponse] = ...

    GetAsJson: grpc.UnaryUnaryMultiCallable[
        ansys.api.geometry.v0.designs_pb2.GetAsJsonRequest,
        ansys.api.geometry.v0.designs_pb2.GetAsJsonResponse] = ...

    GetAssembly: grpc.UnaryUnaryMultiCallable[
        ansys.api.geometry.v0.models_pb2.EntityIdentifier,
        ansys.api.geometry.v0.designs_pb2.GetAssemblyResponse] = ...


class DesignsServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Get(self,
        request: ansys.api.geometry.v0.models_pb2.EntityIdentifier,
        context: grpc.ServicerContext,
    ) -> ansys.api.geometry.v0.models_pb2.Design: ...

    @abc.abstractmethod
    def GetAll(self,
        request: ansys.api.geometry.v0.models_pb2.Empty,
        context: grpc.ServicerContext,
    ) -> ansys.api.geometry.v0.designs_pb2.GetAllResponse: ...

    @abc.abstractmethod
    def GetActive(self,
        request: ansys.api.geometry.v0.models_pb2.Empty,
        context: grpc.ServicerContext,
    ) -> ansys.api.geometry.v0.models_pb2.Design: ...

    @abc.abstractmethod
    def PutActive(self,
        request: ansys.api.geometry.v0.models_pb2.EntityIdentifier,
        context: grpc.ServicerContext,
    ) -> ansys.api.geometry.v0.models_pb2.Empty: ...

    @abc.abstractmethod
    def Open(self,
        request: ansys.api.geometry.v0.designs_pb2.OpenRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.geometry.v0.models_pb2.EntityIdentifier: ...

    @abc.abstractmethod
    def New(self,
        request: ansys.api.geometry.v0.designs_pb2.NewRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.geometry.v0.models_pb2.Design: ...

    @abc.abstractmethod
    def Close(self,
        request: ansys.api.geometry.v0.models_pb2.EntityIdentifier,
        context: grpc.ServicerContext,
    ) -> ansys.api.geometry.v0.models_pb2.Empty: ...

    @abc.abstractmethod
    def Save(self,
        request: ansys.api.geometry.v0.models_pb2.EntityIdentifier,
        context: grpc.ServicerContext,
    ) -> ansys.api.geometry.v0.models_pb2.Empty: ...

    @abc.abstractmethod
    def SaveAs(self,
        request: ansys.api.geometry.v0.designs_pb2.SaveAsRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.geometry.v0.models_pb2.EntityIdentifier: ...

    @abc.abstractmethod
    def Insert(self,
        request: ansys.api.geometry.v0.designs_pb2.InsertRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.geometry.v0.models_pb2.EntityIdentifier: ...

    @abc.abstractmethod
    def Export(self,
        request: ansys.api.geometry.v0.designs_pb2.ExportRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.geometry.v0.designs_pb2.ExportResponse: ...

    @abc.abstractmethod
    def GetAsJson(self,
        request: ansys.api.geometry.v0.designs_pb2.GetAsJsonRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.geometry.v0.designs_pb2.GetAsJsonResponse: ...

    @abc.abstractmethod
    def GetAssembly(self,
        request: ansys.api.geometry.v0.models_pb2.EntityIdentifier,
        context: grpc.ServicerContext,
    ) -> ansys.api.geometry.v0.designs_pb2.GetAssemblyResponse: ...


def add_DesignsServicer_to_server(servicer: DesignsServicer, server: grpc.Server) -> None: ...
