# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ansys.api.geometry.v0 import geometryapi_pb2 as ansys_dot_api_dot_geometry_dot_v0_dot_geometryapi__pb2


class GeometryApiStub(object):
    """Api

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetVersion = channel.unary_unary(
                '/ansys.api.geometry.v0.GeometryApi.GeometryApi/SetVersion',
                request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_geometryapi__pb2.SetVersionRequest.SerializeToString,
                response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_geometryapi__pb2.SetVersionResponse.FromString,
                )
        self.GetVersion = channel.unary_unary(
                '/ansys.api.geometry.v0.GeometryApi.GeometryApi/GetVersion',
                request_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_geometryapi__pb2.GetVersionRequest.SerializeToString,
                response_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_geometryapi__pb2.GetVersionResponse.FromString,
                )


class GeometryApiServicer(object):
    """Api

    """

    def SetVersion(self, request, context):
        """Sets the current scripting version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Sets the current scripting version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeometryApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVersion,
                    request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_geometryapi__pb2.SetVersionRequest.FromString,
                    response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_geometryapi__pb2.SetVersionResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=ansys_dot_api_dot_geometry_dot_v0_dot_geometryapi__pb2.GetVersionRequest.FromString,
                    response_serializer=ansys_dot_api_dot_geometry_dot_v0_dot_geometryapi__pb2.GetVersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ansys.api.geometry.v0.GeometryApi.GeometryApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GeometryApi(object):
    """Api

    """

    @staticmethod
    def SetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.geometry.v0.GeometryApi.GeometryApi/SetVersion',
            ansys_dot_api_dot_geometry_dot_v0_dot_geometryapi__pb2.SetVersionRequest.SerializeToString,
            ansys_dot_api_dot_geometry_dot_v0_dot_geometryapi__pb2.SetVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.geometry.v0.GeometryApi.GeometryApi/GetVersion',
            ansys_dot_api_dot_geometry_dot_v0_dot_geometryapi__pb2.GetVersionRequest.SerializeToString,
            ansys_dot_api_dot_geometry_dot_v0_dot_geometryapi__pb2.GetVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
