
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-06T17:24:59+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ae848335dc80b110910cb33ed3d507fc9f3c467c",
 "version": "v2.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
