
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-10T09:16:22+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "7bb12c64b3e8714a96429715c83109e06aa189da",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
