
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-06T04:38:35-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1409c24cbea0c338dcc66e5ded41e7f3f4d0c1fc",
 "version": "5.4.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
