# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai/lzy/v1/validation/validation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ai/lzy/v1/validation/validation.proto',
  package='ai.lzy.v1.validation',
  syntax='proto3',
  serialized_options=b'\n\024ai.lzy.v1.validationB\002LV',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n%ai/lzy/v1/validation/validation.proto\x12\x14\x61i.lzy.v1.validation\x1a google/protobuf/descriptor.proto:3\n\tsensitive\x12\x1d.google.protobuf.FieldOptions\x18\xcd\x98\xd2\t \x01(\x08\x42\x1a\n\x14\x61i.lzy.v1.validationB\x02LVb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


SENSITIVE_FIELD_NUMBER = 20221005
sensitive = _descriptor.FieldDescriptor(
  name='sensitive', full_name='ai.lzy.v1.validation.sensitive', index=0,
  number=20221005, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)

DESCRIPTOR.extensions_by_name['sensitive'] = sensitive
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(sensitive)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
