VERSION_YEAR = 2023
VERSION_MONTH = int('09')
VERSION_DAY = int('06')
VERSION_HOUR = int('02')
VERSION_MINUTE = int('29')
MAJOR_VERSION = 0
MINOR_VERSION = 31
PATCH_VERSION = 202309060229
version_date = '2023/09/06 02:29'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
