
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-08T10:09:29+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "054154e50a5d3b0fd8a286647a285a5198151446",
 "version": "0.4.0.post0.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
