# coding: utf-8

"""
    OpenAPI Petstore

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal


class RequiredOrder(TypedDict):
    pass

class OptionalOrder(TypedDict, total=False):
    id: int

    petId: int

    quantity: int

    shipDate: datetime

    # Order Status
    status: str

    complete: bool

class Order(RequiredOrder, OptionalOrder):
    pass
