# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: th2_grpc_conn/conn.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18th2_grpc_conn/conn.proto\"\"\n\x0cStartRequest\x12\x12\n\nstop_after\x18\x01 \x01(\r\"\r\n\x0bStopRequest\"a\n\x08Response\x12 \n\x06status\x18\x01 \x01(\x0e\x32\x10.Response.Status\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x32J\n\x04\x43onn\x12!\n\x05start\x12\r.StartRequest\x1a\t.Response\x12\x1f\n\x04stop\x12\x0c.StopRequest\x1a\t.ResponseB\x1e\n\x1a\x63om.exactpro.th2.conn.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'th2_grpc_conn.conn_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.exactpro.th2.conn.grpcP\001'
  _globals['_STARTREQUEST']._serialized_start=28
  _globals['_STARTREQUEST']._serialized_end=62
  _globals['_STOPREQUEST']._serialized_start=64
  _globals['_STOPREQUEST']._serialized_end=77
  _globals['_RESPONSE']._serialized_start=79
  _globals['_RESPONSE']._serialized_end=176
  _globals['_RESPONSE_STATUS']._serialized_start=142
  _globals['_RESPONSE_STATUS']._serialized_end=176
  _globals['_CONN']._serialized_start=178
  _globals['_CONN']._serialized_end=252
# @@protoc_insertion_point(module_scope)
