# Generated by Django 4.0 on 2022-10-26 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_fidnumber_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpSpecialize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empspecialize', to='employee.employee')),
            ],
        ),
    ]
