# Generated by Django 4.0 on 2022-10-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_empspecialize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empspecialize',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Epecialidade'),
        ),
    ]
