# Generated by Django 3.2 on 2022-11-22 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0007_adninfo'),
        ('employee', '0009_alter_empspecialize_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='formaleducation',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.year'),
        ),
    ]
