# Generated by Django 3.2 on 2022-11-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_auto_20221130_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='e_phone1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nu. Telefone Emergensia I'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='e_phone2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nu. Telefone Emergensia II'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nu. Telefone I'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nu. Telefone II'),
        ),
    ]
