# Generated by Django 3.2 on 2022-11-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_auto_20221130_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='e_address1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Emergency Contact Address I'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='e_address2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Emergency Contact Address II'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='e_person1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Emergency Call Fullname I'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='e_person2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Emergency Call Fullname II'),
        ),
    ]
