# Generated by Django 3.2 on 2023-02-14 13:39

import django.core.validators
from django.db import migrations, models
import settings_app.upload_utils


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_emplanguage_file_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=settings_app.upload_utils.upload_photo, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), django.core.validators.MaxValueValidator(524288.0)]),
        ),
    ]
