# Generated by Django 3.2 on 2023-02-23 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_alter_photo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fidnumber',
            options={'verbose_name': 'Financial', 'verbose_name_plural': 'Financials'},
        ),
    ]
