from .module import *

class Module :
    def __init__ (self, uri: str, cache_path: str="module.pymodule") : ...
    
    def download (self) -> int : ...
    
    def deleteCachedFile (self) : ...
    
    def loadCachedFile (self) : ...

    def downloadThenLoad (self) : ...