# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sanctumlabs/messageschema/events/v1/events.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0sanctumlabs/messageschema/events/v1/events.proto\x12#sanctumlabs.messageschema.events.v1\x1a google/protobuf/descriptor.proto:7\n\x06\x64omain\x12\x1c.google.protobuf.FileOptions\x18\x85\x8f\xcb\x05 \x01(\tR\x06\x64omain:;\n\x08grouping\x12\x1c.google.protobuf.FileOptions\x18\x86\x8f\xcb\x05 \x01(\tR\x08grouping:A\n\nevent_type\x12\x1f.google.protobuf.MessageOptions\x18\x87\x8f\xcb\x05 \x01(\tR\teventType:6\n\x04tags\x12\x1f.google.protobuf.MessageOptions\x18\x88\x8f\xcb\x05 \x03(\tR\x04tagsBm\n*com.sanctumlabs.messageschema.events.modelB\x0b\x45ventsProtoP\x01Z0sanctumlabs/libraries/messageschema/events/modelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sanctumlabs.messageschema.events.v1.events_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(domain)
  google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(grouping)
  google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(event_type)
  google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(tags)

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n*com.sanctumlabs.messageschema.events.modelB\013EventsProtoP\001Z0sanctumlabs/libraries/messageschema/events/model'
# @@protoc_insertion_point(module_scope)
