DISABLE = 0
ENABLE = 1

SEQ_CMD_RUN = 1
SEQ_CMD_RESET = 2

TRIG_MODE_POSITIVE_EDGE = 0
TRIG_MODE_NEGATIVE_EDGE = 1
TRIG_MODE_HIGH_LEVEL = 2
TRIG_MODE_LOW_LEVEL = 3

TRIG_SOURCE_NONE = 0
TRIG_SOURCE_ELECTRICAL = 1 << 0
TRIG_SOURCE_OPTICAL = 1 << 1
TRIG_SOURCE_INTERNAL = 1 << 2
TRIG_SOURCE_SOFTWARE = 1 << 3
TRIG_SOURCE_DELAYED = 1 << 4

DMD_TYPE_1080P_A = 0
DMD_TYPE_XGA_A = 1
DMD_TYPE_XGA_X = 3
DMD_TYPE_WUXGA_A = 5
DMD_TYPE_UNKNOWN = 99
DMD_TYPE_NO_DMD_CONNECTED = 15

