# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ConnectSessionTokenCategoriesItem(str, enum.Enum):
    ATS = "ats"
    HRIS = "hris"
    CRM = "crm"
    MARKETING = "marketing"
    COMMON = "common"

    def visit(
        self,
        ats: typing.Callable[[], T_Result],
        hris: typing.Callable[[], T_Result],
        crm: typing.Callable[[], T_Result],
        marketing: typing.Callable[[], T_Result],
        common: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is ConnectSessionTokenCategoriesItem.ATS:
            return ats()
        if self is ConnectSessionTokenCategoriesItem.HRIS:
            return hris()
        if self is ConnectSessionTokenCategoriesItem.CRM:
            return crm()
        if self is ConnectSessionTokenCategoriesItem.MARKETING:
            return marketing()
        if self is ConnectSessionTokenCategoriesItem.COMMON:
            return common()
