APPLICATION_ENDPOINT = "/apps/"
SINGLE_APPLICATION_ENDPOINT = APPLICATION_ENDPOINT + "{id}"
APPLICATION_DATA_ENDPOINT = f"{SINGLE_APPLICATION_ENDPOINT}/data"
APPLICATION_ACTIONS_ENDPOINT = f"{SINGLE_APPLICATION_ENDPOINT}/actions"

DEFAULT_APPS_PAGE_SIZE = 50
