# Generated by Django 4.0 on 2022-09-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_curempposition_curempdivision'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_new',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
