# Generated by Django 4.0 on 2022-09-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='blood',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='father',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mother',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
