# Generated by Django 4.0 on 2022-10-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_blood_alter_employee_father_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fidnumber',
            name='bank_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Enderesu Banku'),
        ),
        migrations.AddField(
            model_name='fidnumber',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naran'),
        ),
        migrations.AlterField(
            model_name='fidnumber',
            name='bank',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Banku'),
        ),
        migrations.AlterField(
            model_name='fidnumber',
            name='bank_account',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nu. Konta'),
        ),
        migrations.AlterField(
            model_name='fidnumber',
            name='payrol_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nu. Payrol'),
        ),
    ]
