# Generated by Django 4.0 on 2022-10-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_fidnumber_bank_address_fidnumber_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fidnumber',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naran Iha Konta'),
        ),
    ]
