# Generated by Django 3.2 on 2022-11-22 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0007_adninfo'),
        ('employee', '0011_nonformaleducation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='end_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_year', to='custom.year'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='start_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_year', to='custom.year'),
        ),
    ]
