# Generated by Django 3.2 on 2022-11-22 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20221122_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='formaleducation',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.empyear'),
        ),
        migrations.AlterField(
            model_name='nonformaleducation',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.empyear'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_year', to='employee.empyear'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_year', to='employee.empyear'),
        ),
    ]
