# Generated by Django 3.2 on 2022-11-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20221122_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='emergency_call',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='e_email1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Emergency Email II'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='e_email2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Emergency Email II'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='e_person1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Call Fullname'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='e_person2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Call Fullname'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='e_phone1',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='Nu. Telefone Emergensia I'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='e_phone2',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='Nu. Telefone Emergensia II'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='o_email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Official Email'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='p_email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Private Email'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='phone1',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='Nu. Telefone I'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='phone2',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='Nu. Telefone II'),
        ),
    ]
