# Generated by Django 3.2 on 2022-11-30 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0007_adninfo'),
        ('employee', '0016_auto_20221130_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='e_relation1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erelation1', to='custom.familyrelation', verbose_name='Relasaun'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='e_relation2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erelation2', to='custom.familyrelation', verbose_name='Relasaun'),
        ),
    ]
