# Generated by Django 3.2 on 2022-12-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_auto_20221130_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
