# Generated by Django 3.2 on 2023-01-19 10:28

import django.core.validators
from django.db import migrations, models
import settings_app.upload_utils


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_auto_20230117_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplanguage',
            name='file_language',
            field=models.FileField(blank=True, null=True, upload_to=settings_app.upload_utils.upload_languages, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Attach Certificado'),
        ),
    ]
