# Generated by Django 3.2 on 2023-03-15 09:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import settings_app.upload_utils


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_alter_fidnumber_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=settings_app.upload_utils.upload_photo, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empsignature', to='employee.employee')),
            ],
        ),
    ]
