# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_const.ipynb.

# %% auto 0
__all__ = ['ABSTRACTMETHOD', 'ISABSTRACTMETHOD', 'DDOT', 'DCLN', 'SPACE', 'SECTIONS', 'NUMPY_SECTIONS', 'PARAMETERS',
           'ATTRIBUTES', 'METHODS', 'RETURNS', 'YIELDS', 'RECEIVES', 'RAISES', 'WARNS', 'SEE_ALSO', 'NOTES',
           'REFERENCES', 'EXAMPLES', 'REST_NOTE', 'REST_MATH', 'REST_WARNING', 'REST_DEPRECATED', 'REST_AUTO_FOOTNOTE',
           'REST_LABEL_FOOTNOTE']

# %% ../nbs/00_const.ipynb 6
ABSTRACTMETHOD = 'abstractmethod'
ISABSTRACTMETHOD = f'__is{ABSTRACTMETHOD}__'

# %% ../nbs/00_const.ipynb 8
DDOT = '..'
DCLN = '::'
SPACE = ' ' # string.whitespace[0]

# %% ../nbs/00_const.ipynb 10
SECTIONS = (
    'parameters', 'attributes', 'methods', 'returns', 'yields', 'receives', 'raises', 
    'warns', 'see also', 'notes', 'references', 'examples'
)

NUMPY_SECTIONS = tuple(map(lambda s: s.title(), SECTIONS))

# %% ../nbs/00_const.ipynb 12
PARAMETERS = 'Parameters'
ATTRIBUTES = 'Attributes'
METHODS = 'Methods'
RETURNS = 'Returns'
YIELDS = 'Yields'
RECEIVES = 'Receives'
RAISES = 'Raises'
WARNS = 'Warns'
SEE_ALSO = 'See Also'
NOTES = 'Notes'
REFERENCES = 'References'
EXAMPLES = 'Examples'

# %% ../nbs/00_const.ipynb 14
REST_NOTE = f'{DDOT} note{DCLN}'
REST_MATH = f'{DDOT} math{DCLN}'
REST_WARNING = f'{DDOT} warning{DCLN}'
REST_DEPRECATED = f'{DDOT} deprecated{DCLN}'
REST_AUTO_FOOTNOTE = f'{DDOT} [*]'
REST_LABEL_FOOTNOTE = f'{DDOT} [#label]'
