# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ....core.datetime_utils import serialize_datetime
from .account_address import AccountAddress


class Account(pydantic.BaseModel):
    id: str
    owner_id: str
    name: str
    description: typing.Optional[str]
    annual_revenue: typing.Optional[str]
    website: typing.Optional[str]
    addresses: typing.Optional[typing.List[AccountAddress]]
    phone_numbers: typing.Optional[typing.List[str]]
    created_at: typing.Optional[str]
    updated_at: typing.Optional[str]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        json_encoders = {dt.datetime: serialize_datetime}
