
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-04T13:56:35+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "400e4ca7c1fa9dc6c51d135c29c33c3cb5c9d766",
 "version": "v1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
