VERSION_YEAR = 2023
VERSION_MONTH = int('09')
VERSION_DAY = int('07')
VERSION_HOUR = int('01')
VERSION_MINUTE = int('19')
MAJOR_VERSION = 0
MINOR_VERSION = 31
PATCH_VERSION = 202309070119
version_date = '2023/09/07 01:19'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
