# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sanctumlabs/messageschema/events/common/v1/common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7sanctumlabs/messageschema/events/common/v1/common.proto\x12*sanctumlabs.messageschema.events.common.v1\x1a\x17validate/validate.proto\"~\n\x11\x43onnectionDetails\x12\x30\n\x0f\x63onnection_type\x18\x01 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01R\x0e\x63onnectionType\x12&\n\x0cnetwork_name\x18\x02 \x01(\tH\x00R\x0bnetworkName\x88\x01\x01\x42\x0f\n\r_network_name\"u\n\x07\x46\x61ilure\x12\x1b\n\x04\x63ode\x18\x01 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01R\x04\x63ode\x12\x1f\n\x06reason\x18\x02 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01R\x06reason\x12\x1f\n\x08\x63\x61tegory\x18\x03 \x01(\tH\x00R\x08\x63\x61tegory\x88\x01\x01\x42\x0b\n\t_category\"\x8c\x02\n\x10\x42\x61sicUserDetails\x12\"\n\nfirst_name\x18\x01 \x01(\tH\x00R\tfirstName\x88\x01\x01\x12$\n\x0bmiddle_name\x18\x02 \x01(\tH\x01R\nmiddleName\x88\x01\x01\x12 \n\tlast_name\x18\x03 \x01(\tH\x02R\x08lastName\x88\x01\x01\x12\x19\n\x05\x65mail\x18\x04 \x01(\tH\x03R\x05\x65mail\x88\x01\x01\x12(\n\rmobile_number\x18\x05 \x01(\tH\x04R\x0cmobileNumber\x88\x01\x01\x42\r\n\x0b_first_nameB\x0e\n\x0c_middle_nameB\x0c\n\n_last_nameB\x08\n\x06_emailB\x10\n\x0e_mobile_numberB{\n4com.sanctumlabs.messageschema.events.model.common.v1B\x0b\x43ommonProtoP\x01Z4sanctumlabs/libraries/messageschema/events/common/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sanctumlabs.messageschema.events.common.v1.common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n4com.sanctumlabs.messageschema.events.model.common.v1B\013CommonProtoP\001Z4sanctumlabs/libraries/messageschema/events/common/v1'
  _CONNECTIONDETAILS.fields_by_name['connection_type']._options = None
  _CONNECTIONDETAILS.fields_by_name['connection_type']._serialized_options = b'\372B\004r\002\020\001'
  _FAILURE.fields_by_name['code']._options = None
  _FAILURE.fields_by_name['code']._serialized_options = b'\372B\004r\002\020\001'
  _FAILURE.fields_by_name['reason']._options = None
  _FAILURE.fields_by_name['reason']._serialized_options = b'\372B\004r\002\020\001'
  _globals['_CONNECTIONDETAILS']._serialized_start=128
  _globals['_CONNECTIONDETAILS']._serialized_end=254
  _globals['_FAILURE']._serialized_start=256
  _globals['_FAILURE']._serialized_end=373
  _globals['_BASICUSERDETAILS']._serialized_start=376
  _globals['_BASICUSERDETAILS']._serialized_end=644
# @@protoc_insertion_point(module_scope)
