# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sanctumlabs/messageschema/messages/notifications/sms/v1/events.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sanctumlabs.messageschema.events.envelope.v1 import envelope_pb2 as sanctumlabs_dot_messageschema_dot_events_dot_envelope_dot_v1_dot_envelope__pb2
from sanctumlabs.messageschema.events.notifications.sms.v1 import events_pb2 as sanctumlabs_dot_messageschema_dot_events_dot_notifications_dot_sms_dot_v1_dot_events__pb2
from sanctumlabs.messageschema.events.v1 import events_pb2 as sanctumlabs_dot_messageschema_dot_events_dot_v1_dot_events__pb2
from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDsanctumlabs/messageschema/messages/notifications/sms/v1/events.proto\x12\x37sanctumlabs.messageschema.messages.notifications.sms.v1\x1a;sanctumlabs/messageschema/events/envelope/v1/envelope.proto\x1a\x42sanctumlabs/messageschema/events/notifications/sms/v1/events.proto\x1a\x30sanctumlabs/messageschema/events/v1/events.proto\x1a\x17validate/validate.proto\"\xc1\x04\n\x05SmsV1\x12\x66\n\x0c\x65vent_fields\x18\x01 \x01(\x0b\x32\x39.sanctumlabs.messageschema.events.envelope.v1.EventFieldsB\x08\xfa\x42\x05\x8a\x01\x02\x10\x01R\x0b\x65ventFields\x12g\n\x0csms_received\x18\x02 \x01(\x0b\x32\x42.sanctumlabs.messageschema.events.notifications.sms.v1.SmsReceivedH\x00R\x0bsmsReceived\x12j\n\rsms_submitted\x18\x03 \x01(\x0b\x32\x43.sanctumlabs.messageschema.events.notifications.sms.v1.SmsSubmittedH\x00R\x0csmsSubmitted\x12[\n\x08sms_sent\x18\x04 \x01(\x0b\x32>.sanctumlabs.messageschema.events.notifications.sms.v1.SmsSentH\x00R\x07smsSent\x12\x80\x01\n\x15sms_callback_received\x18\x05 \x01(\x0b\x32J.sanctumlabs.messageschema.events.notifications.sms.v1.SmsCallbackReceivedH\x00R\x13smsCallbackReceived:\x0b\xba\xf8\xd8,\x06sms_v1B\x0e\n\x07payload\x12\x03\xf8\x42\x01\x42\xb5\x01\n;com.sanctumlabs.messageschema.messages.notifications.sms.v1B\rSmsTopicProtoP\x01ZAsanctumlabs/libraries/messageschema/messages/notifications/sms/v1\xaa\xf8\xd8,\rnotifications\xb2\xf8\xd8,\rnotificationsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sanctumlabs.messageschema.messages.notifications.sms.v1.events_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n;com.sanctumlabs.messageschema.messages.notifications.sms.v1B\rSmsTopicProtoP\001ZAsanctumlabs/libraries/messageschema/messages/notifications/sms/v1\252\370\330,\rnotifications\262\370\330,\rnotifications'
  _SMSV1.oneofs_by_name['payload']._options = None
  _SMSV1.oneofs_by_name['payload']._serialized_options = b'\370B\001'
  _SMSV1.fields_by_name['event_fields']._options = None
  _SMSV1.fields_by_name['event_fields']._serialized_options = b'\372B\005\212\001\002\020\001'
  _SMSV1._options = None
  _SMSV1._serialized_options = b'\272\370\330,\006sms_v1'
  _globals['_SMSV1']._serialized_start=334
  _globals['_SMSV1']._serialized_end=911
# @@protoc_insertion_point(module_scope)
