# Generated by Django 4.2.4 on 2023-08-29 03:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("artd_stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stock",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
            },
        ),
    ]
