# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sanctumlabs/messageschema/messages/signup/v1/events.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sanctumlabs.messageschema.events.envelope.v1 import envelope_pb2 as sanctumlabs_dot_messageschema_dot_events_dot_envelope_dot_v1_dot_envelope__pb2
from sanctumlabs.messageschema.events.signup.v1 import events_pb2 as sanctumlabs_dot_messageschema_dot_events_dot_signup_dot_v1_dot_events__pb2
from sanctumlabs.messageschema.events.v1 import events_pb2 as sanctumlabs_dot_messageschema_dot_events_dot_v1_dot_events__pb2
from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9sanctumlabs/messageschema/messages/signup/v1/events.proto\x12,sanctumlabs.messageschema.messages.signup.v1\x1a;sanctumlabs/messageschema/events/envelope/v1/envelope.proto\x1a\x37sanctumlabs/messageschema/events/signup/v1/events.proto\x1a\x30sanctumlabs/messageschema/events/v1/events.proto\x1a\x17validate/validate.proto\"\xf6\x01\n\x08SignupV1\x12\x66\n\x0c\x65vent_fields\x18\x01 \x01(\x0b\x32\x39.sanctumlabs.messageschema.events.envelope.v1.EventFieldsB\x08\xfa\x42\x05\x8a\x01\x02\x10\x01R\x0b\x65ventFields\x12\x62\n\x0esignup_started\x18\x02 \x01(\x0b\x32\x39.sanctumlabs.messageschema.events.signup.v1.SignupStartedH\x00R\rsignupStarted:\x0e\xba\xf8\xd8,\tsignup_v1B\x0e\n\x07payload\x12\x03\xf8\x42\x01\x42\x94\x01\n0com.sanctumlabs.messageschema.messages.signup.v1B\x10SignupTopicProtoP\x01Z6sanctumlabs/libraries/messageschema/messages/signup/v1\xaa\xf8\xd8,\x06signup\xb2\xf8\xd8,\x06signupb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sanctumlabs.messageschema.messages.signup.v1.events_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n0com.sanctumlabs.messageschema.messages.signup.v1B\020SignupTopicProtoP\001Z6sanctumlabs/libraries/messageschema/messages/signup/v1\252\370\330,\006signup\262\370\330,\006signup'
  _SIGNUPV1.oneofs_by_name['payload']._options = None
  _SIGNUPV1.oneofs_by_name['payload']._serialized_options = b'\370B\001'
  _SIGNUPV1.fields_by_name['event_fields']._options = None
  _SIGNUPV1.fields_by_name['event_fields']._serialized_options = b'\372B\005\212\001\002\020\001'
  _SIGNUPV1._options = None
  _SIGNUPV1._serialized_options = b'\272\370\330,\tsignup_v1'
  _globals['_SIGNUPV1']._serialized_start=301
  _globals['_SIGNUPV1']._serialized_end=547
# @@protoc_insertion_point(module_scope)
