# coding: utf-8

"""
    scibec

    scibec  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: klaus.wakonig@psi.ch
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.access_config_scope_filter import AccessConfigScopeFilter
from openapi_client import configuration


class TestAccessConfigScopeFilter(unittest.TestCase):
    """AccessConfigScopeFilter unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
