# coding: utf-8

"""
    scibec

    scibec  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: klaus.wakonig@psi.ch
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.beamline_include_filter_items import BeamlineIncludeFilterItems
from openapi_client import configuration


class TestBeamlineIncludeFilterItems(unittest.TestCase):
    """BeamlineIncludeFilterItems unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
