# coding: utf-8

"""
    scibec

    scibec  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: klaus.wakonig@psi.ch
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.beamline_with_relations import BeamlineWithRelations
from openapi_client import configuration


class TestBeamlineWithRelations(unittest.TestCase):
    """BeamlineWithRelations unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
