
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-06T12:45:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "852b75817234c986f872ebab62dbdb6d49e8f972",
 "version": "1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
