
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-08T10:38:31+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "29c5f36c62f27667632d639013dcfaf6a6920af9",
 "version": "2.19.1b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
