# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from th2_grpc_conn import conn_pb2 as th2__grpc__conn_dot_conn__pb2


class ConnStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.start = channel.unary_unary(
                '/Conn/start',
                request_serializer=th2__grpc__conn_dot_conn__pb2.StartRequest.SerializeToString,
                response_deserializer=th2__grpc__conn_dot_conn__pb2.Response.FromString,
                )
        self.stop = channel.unary_unary(
                '/Conn/stop',
                request_serializer=th2__grpc__conn_dot_conn__pb2.StopRequest.SerializeToString,
                response_deserializer=th2__grpc__conn_dot_conn__pb2.Response.FromString,
                )


class ConnServicer(object):
    """Missing associated documentation comment in .proto file."""

    def start(self, request, context):
        """starts connect
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stop(self, request, context):
        """stops connect
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'start': grpc.unary_unary_rpc_method_handler(
                    servicer.start,
                    request_deserializer=th2__grpc__conn_dot_conn__pb2.StartRequest.FromString,
                    response_serializer=th2__grpc__conn_dot_conn__pb2.Response.SerializeToString,
            ),
            'stop': grpc.unary_unary_rpc_method_handler(
                    servicer.stop,
                    request_deserializer=th2__grpc__conn_dot_conn__pb2.StopRequest.FromString,
                    response_serializer=th2__grpc__conn_dot_conn__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Conn', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Conn(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Conn/start',
            th2__grpc__conn_dot_conn__pb2.StartRequest.SerializeToString,
            th2__grpc__conn_dot_conn__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Conn/stop',
            th2__grpc__conn_dot_conn__pb2.StopRequest.SerializeToString,
            th2__grpc__conn_dot_conn__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
