
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-02T17:50:30+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "f9725d0c7752ff047363bf3084df177c84dc1ad6",
 "version": "1.3.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
