"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _EmailStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EmailStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EmailStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    EMAIL_STATUS_UNSPECIFIED: _EmailStatus.ValueType  # 0
    ACCEPTED: _EmailStatus.ValueType  # 1
    SCHEDULED: _EmailStatus.ValueType  # 2
    CANCELED: _EmailStatus.ValueType  # 3
    QUEUED: _EmailStatus.ValueType  # 4
    SENDING: _EmailStatus.ValueType  # 5
    SENT: _EmailStatus.ValueType  # 6
    FAILED: _EmailStatus.ValueType  # 7
    DELIVERED: _EmailStatus.ValueType  # 8
    UNDELIVERED: _EmailStatus.ValueType  # 9
    RECEIVING: _EmailStatus.ValueType  # 10
    READ: _EmailStatus.ValueType  # 11
    PENDING: _EmailStatus.ValueType  # 12

class EmailStatus(_EmailStatus, metaclass=_EmailStatusEnumTypeWrapper):
    """EMAILStatus is the status of the EMAIL"""

EMAIL_STATUS_UNSPECIFIED: EmailStatus.ValueType  # 0
ACCEPTED: EmailStatus.ValueType  # 1
SCHEDULED: EmailStatus.ValueType  # 2
CANCELED: EmailStatus.ValueType  # 3
QUEUED: EmailStatus.ValueType  # 4
SENDING: EmailStatus.ValueType  # 5
SENT: EmailStatus.ValueType  # 6
FAILED: EmailStatus.ValueType  # 7
DELIVERED: EmailStatus.ValueType  # 8
UNDELIVERED: EmailStatus.ValueType  # 9
RECEIVING: EmailStatus.ValueType  # 10
READ: EmailStatus.ValueType  # 11
PENDING: EmailStatus.ValueType  # 12
global___EmailStatus = EmailStatus

@typing_extensions.final
class Email(google.protobuf.message.Message):
    """Email is is the email message to deliver"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    FROM_FIELD_NUMBER: builtins.int
    TO_FIELD_NUMBER: builtins.int
    CC_FIELD_NUMBER: builtins.int
    BCC_FIELD_NUMBER: builtins.int
    SUBJECT_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    ATTACHMENTS_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    id: builtins.str
    @property
    def to(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """to is the recipient of the message. this is required"""
    @property
    def cc(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """cc is the list of carbon copy recipients of this email. This could be an empty list"""
    @property
    def bcc(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """bcc is the list of carbon copy recipients of this email. This could be an empty list"""
    subject: builtins.str
    """subject is the subject of the email to send out"""
    message: builtins.str
    """message is the email body containing the message to send out"""
    @property
    def attachments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EmailAttachment]:
        """attachments is a list of optional attachments to add to the email message"""
    status: global___EmailStatus.ValueType
    """status is the state of deliver of this email"""
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        to: collections.abc.Iterable[builtins.str] | None = ...,
        cc: collections.abc.Iterable[builtins.str] | None = ...,
        bcc: collections.abc.Iterable[builtins.str] | None = ...,
        subject: builtins.str = ...,
        message: builtins.str = ...,
        attachments: collections.abc.Iterable[global___EmailAttachment] | None = ...,
        status: global___EmailStatus.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_from", b"_from", "_status", b"_status", "from", b"from", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_from", b"_from", "_status", b"_status", "attachments", b"attachments", "bcc", b"bcc", "cc", b"cc", "from", b"from", "id", b"id", "message", b"message", "status", b"status", "subject", b"subject", "to", b"to"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_from", b"_from"]) -> typing_extensions.Literal["from"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_status", b"_status"]) -> typing_extensions.Literal["status"] | None: ...

global___Email = Email

@typing_extensions.final
class EmailAttachment(google.protobuf.message.Message):
    """EmailAttachment represents an attachment in an email message"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTENT_FIELD_NUMBER: builtins.int
    FILENAME_FIELD_NUMBER: builtins.int
    MIMETYPE_FIELD_NUMBER: builtins.int
    content: builtins.str
    """content of the attachment"""
    filename: builtins.str
    """filename of the attachment"""
    mimetype: builtins.str
    """mimetype of the attachment"""
    def __init__(
        self,
        *,
        content: builtins.str = ...,
        filename: builtins.str = ...,
        mimetype: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["content", b"content", "filename", b"filename", "mimetype", b"mimetype"]) -> None: ...

global___EmailAttachment = EmailAttachment
