
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-06T12:02:59+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "10cfee9e36492e7b42d74d13f865ae17eb58c91a",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
