
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-08T15:19:46+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "57ebad81bbc28304f108e33585b7b7fd6e71e042",
 "version": "0.7.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
